NAME	=	serializer

CPP		=	c++ -Wall -Wextra -Werror -std=c++98

SRC		=	main.cpp					\
			Serializer.cpp				\

all		:
	$(CPP) $(SRC) -o $(NAME)

clean	:
	rm -f $(NAME)

fclean	:	clean

re		:	fclean all